# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tPNONS-Y0H5CFpv7dxQ9Q4eXKo3zChN5
"""

import pandas as pd

data=pd.read_csv("tmppj4rb047.csv")

data.head()

data.OFFENSE_CODE_GROUP.value_counts().iloc[:10]

data.OFFENSE_CODE_GROUP.value_counts().iloc[:10].sort_values().plot(kind= "barh")

medical = data[data.OFFENSE_CODE_GROUP.str.contains("Medical Assistance")]
medical.head()

medical.groupby("STREET").size().sort_values(ascending = False)



medical.groupby("MONTH").size().plot(kind = "bar")

medical.groupby("HOUR").size().plot(kind= "bar")

medical[medical.YEAR == 2019].groupby(["MONTH", "HOUR"]).size()

